{
 "title": "Clouddriver",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "spinSvc", "query": "clouddriver" },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{job=~\".*$spinSvc.*\"}, job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "Account",
    "query": {
     "query": "label_values(controller_invocations_total{job=~\"$job\"}, account)"
    }
   },
   {
    "name": "Platform",
    "query": "google,aws,kubernetes,docker,appengine,dcos"
   }
  ]
 },
 "panels": [
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "This srvice is the main integration point for Spinnaker cloud providers like AWS, Azure, CloudFoundry, GCP, Kubernetes, etc."
   }
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$Account 5xx Errors (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\",instance=~\"$Instance\",status=\"5xx\",account=~\"$Account\"}[$__rate_interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Validation Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "validationErrors_total", "legendFormat": "{{operation}}" }
   ]
  },
  { "title": "Operations and Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$Account Controller Invocation by Method (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__rate_interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Operation Failures by Operation (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__rate_interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "$Account Controller Invocation Latency by Method (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(operations_seconds_sum{success!=\"true\"}[$__rate_interval])) by (OperationType)\n/\nsum(rate(operations_seconds_count[$__rate_interval])) by (OperationType)",
     "legendFormat": "{{OperationType}}"
    },
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__rate_interval])) by (controller, method) \n/\nsum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__rate_interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Tasks per Instance (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tasks_total{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operations by Operation (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(operations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval])) by (OperationType)",
     "legendFormat": "{{OperationType}}"
    }
   ]
  },
  {
   "title": "Execution Count by Instance (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(executionTime_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Time by Operation (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(operations_seconds_sum{job=~\"$job\",instance=~\"$Instance\"}[$__rate_interval])) by (OperationType)\n/\nsum(rate(operations_seconds_count{job=~\"$job\",instance=~\"$Instance\"}[$__rate_interval])) by (OperationType)",
     "legendFormat": "{{OperationType}}"
    }
   ]
  },
  {
   "title": "Execution Latency by Instance (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(executionTime_seconds_sum{job=~\"$job\",instance=~\"$Instance\"}[$__rate_interval])) by (instance)\n/\nsum(rate(executionTime_seconds_count{job=~\"$job\",instance=~\"$Instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "On Demand Reads by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(onDemand_read_seconds_count{job=~\"$job\",providerName=~\".*$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (onDemandType)",
     "legendFormat": "{{onDemandType}}"
    }
   ]
  },
  {
   "title": "Cache Agent Execution by Account (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (provider, account) (\n# provider\nlabel_replace(\n# account\nlabel_replace(\n# query\n(sum(rate(executionTime_seconds_count{job=~\"$job\", agent=~\".*$Platform.*\",instance=~\"$Instance\"}[$__rate_interval])) by (agent)\n),\n\"account\", \"$1\", \"agent\", \"^[A-Za-z]+/([A-Za-z0-9-]+).*\"\n), \n\"provider\", \"$1\", \"agent\", \"^([A-Za-z]+).*\"\n)\n)",
     "legendFormat": "{{ provider }} :: {{ account }}"
    }
   ]
  },
  {
   "title": "On Demand Read Latency by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(onDemand_read_seconds_sum{job=~\"$job\",providerName=~\".*$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (onDemandType)\n/\nsum(rate(onDemand_read_seconds_count{job=~\"$job\",providerName=~\".*$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (onDemandType)",
     "legendFormat": "{{onDemandType}}"
    }
   ]
  },
  { "title": "SQL Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Cache Agent Execution Latency by Account (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (provider, account) (\n# provider\nlabel_replace(\n# account\nlabel_replace(\n# query\n(sum(rate(executionTime_seconds_sum{job=~\"$job\", agent=~\".*$Platform.*\",instance=~\"$Instance\"}[$__rate_interval])) by (agent)\n),\n\"account\", \"$1\", \"agent\", \"^[A-Za-z]+/([A-Za-z0-9-]+).*\"\n), \n\"provider\", \"$1\", \"agent\", \"^([A-Za-z]+).*\"\n)\n)\n\n/\n\nsum by (provider, account) (\n# provider\nlabel_replace(\n# account\nlabel_replace(\n# query\n(sum(rate(executionTime_seconds_count{job=~\"$job\", agent=~\".*$Platform.*\",instance=~\"$Instance\"}[$__rate_interval])) by (agent)\n),\n\"account\", \"$1\", \"agent\", \"^[A-Za-z]+/([A-Za-z0-9-]+).*\"\n), \n\"provider\", \"$1\", \"agent\", \"^([A-Za-z]+).*\"\n)\n)",
     "legendFormat": "{{ provider }} :: {{ account }}"
    }
   ]
  },
  {
   "title": "CATS Relationships Requested by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_relationshipsRequested_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_relationshipsRequested_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Relationships Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_get_relationshipsRequested_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_get_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Relationships Written by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_relationshipCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_relationshipCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Relationships Written by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_merge_relationshipCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_merge_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_evict_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_evict_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_evict_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Redis Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CATS Keys Requested by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_keysRequested_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_keysRequested_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_get_keysRequested_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_get_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Keys Written by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_keysWritten_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_keysWritten_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Written by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_merge_keysWritten_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")"
    }
   ]
  },
  {
   "title": "CATS Items Written by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_merge_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Deleted by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Deleted by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_evict_keysDeleted_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Platform (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__rate_interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Type (clouddriver, $Instance, $Platform)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_evict_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "TODO - Google Operations - Confirm metric names",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }
  },
  {
   "title": "Google Operation Failures (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google Operation Wait Until Done Time (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",status!=\"DONE\"}[$__rate_interval])) by (basePhase, scope) ",
     "legendFormat": "{{scope}}/{{basePhase}}"
    },
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__totalTime_total{instance=~\"$Instance\"}[$__rate_interval])) by (basePhase, scope) / sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\"}[$__rate_interval])) by (basePhase, scope) ",
     "legendFormat": "{{scope}}/{{basePhase}}"
    },
    {
     "expr": "sum((clouddriver:google:operationWaits__totalTime_total{instance=~\"$Instance\"})) by (basePhase, scope) / sum((clouddriver:google:operationWaits__count_total{instance=~\"$Instance\"})) by (basePhase, scope) ",
     "legendFormat": "{{scope}}/{{basePhase}}"
    },
    {
     "expr": "clouddriver:google:operationWaits__count_total{instance=~\"$Instance\"}"
    },
    {
     "expr": "clouddriver:google:operationWaitRequests",
     "legendFormat": "{{scope}}/{{basePhase}}"
    }
   ]
  },
  {
   "title": "Google Operations Started (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google Operation Success (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",status=\"DONE\"}[$__rate_interval])) by (basePhase)",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  { "title": "Amazon Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Amazon Client Rate Limiting by ClientType (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(amazonClientProvider_rateLimitDelayMil[$__rate_interval])) by (clientType)",
     "legendFormat": "{{clientType}}"
    }
   ]
  },
  {
   "title": "$Account Cache Drift by Region/Agent (clouddriver, $Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n# query\navg(cache_drift{account=~\"$Account\", instance=~\"$Instance\"}) by (account, agent, region),\n\"agent\", \"$1\", \"agent\",  \"(.*)CachingAgent\"\n)",
     "legendFormat": "{{account}}/{{region}}/{{agent}}"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Inbound Request Rate by Method",
   "type": "timeseries",
   "description": "Inbound HTTP requests. \n\n`controller_invocations_total` is an enhanced version of Spring `http_server_requests_seconds_count` with additional labels.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum by (controller, method) (rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Inbound Request Latency by Method",
   "type": "timeseries",
   "description": "Inbound HTTP request latencies. \n\n`controller_invocations_total` is an enhanced version of Spring `http_server_requests_seconds_count` with additional labels.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "expr": "sum by (controller, method) (rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval]))\n / \n sum by (controller, method) (rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Inbound Request Errors by Method",
   "type": "timeseries",
   "description": "Inbound HTTP request errors. \n\n`controller_invocations_total` is an enhanced version of Spring `http_server_requests_seconds_count` with additional labels.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "expr": "sum by (statusCode, cause, controller, method) (rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\", status=\"5xx\"}[$__rate_interval]))",
     "legendFormat": "{{statusCode}}/{{cause}}/{{controller}}/{{method}}"
    },
    {
     "expr": "sum by (statusCode, cause, controller, method) (rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\", statusCode=\"429\"}[$__rate_interval]))",
     "legendFormat": "{{statusCode}}/{{cause}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Outbound Request Rate",
   "type": "timeseries",
   "description": "Rate of outbound http requests to other Spinnaker services.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum by (requestHost) (rate(okhttp_requests_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{requestHost}}"
    }
   ]
  },
  {
   "title": "Outbound Request Latency",
   "type": "timeseries",
   "description": "Latency of outbound http requests to other Spinnaker services.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
   "targets": [
    {
     "expr": "sum by (requestHost) (rate(okhttp_requests_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval]))\n / \n sum by (requestHost) (rate(okhttp_requests_seconds_count{job=\"$job\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{requestHost}}"
    }
   ]
  },
  {
   "title": "Outbound Request Error Rate",
   "type": "timeseries",
   "description": "Rate of outbound http request errors when calling other Spinnaker services. \n\nCheck the logs looking for `retrofit error` or `<--- 500`",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
   "targets": [
    {
     "expr": "sum by (requestHost, statusCode) (rate(okhttp_requests_seconds_count{job=~\"$job\", instance=~\"$Instance\", status=~\"(5xx|Unknown)\"}[$__rate_interval]))",
     "legendFormat": "{{statusCode}}/{{status}}/{{requestHost}}"
    },
    {
     "expr": "sum by (requestHost, statusCode) (rate(okhttp_requests_seconds_count{job=~\"$job\", instance=~\"$Instance\", statusCode=\"429\"}[$__rate_interval]))",
     "legendFormat": "{{statusCode}}/{{requestHost}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\", area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "JVM GC Average Pause Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 114 },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_gc_pause_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}) \n / \n sum by (instance) (jvm_gc_pause_seconds_count{job=~\"$job\", instance=~\"$Instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Maximum Pause Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "max by (instance) (jvm_gc_pause_seconds_max{job=~\"$job\", instance=~\"$Instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 114 },
   "targets": [
    {
     "expr": "max_over_time(jvm_threads_live_threads{job=~\"$job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kubernetes Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU Usage. Average is the average usage across all instances, max is the highest usage across all instances. As CPU Usage is a sampled metric it is best to view in relation to throttling percentage.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=~\"$spinSvc\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container=\"$spinSvc\"}[$__rate_interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=\"$spinSvc\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"$spinSvc\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "description": "Percent of the time that the CPU is being throttled. Application may be getting throttled during bursty tasks but overall be well below its CPU limit. Throttling may significantly impact application performance.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 122 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container=\"$spinSvc\"}[$__rate_interval])\n/\nrate(container_cpu_cfs_periods_total{container=\"$spinSvc\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory utilisation. Average is the average usage across all instaces, max is the highest usage across all instances.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "avg(avg_over_time(container_memory_working_set_bytes{container=\"$spinSvc\"}[$__interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(max_over_time(container_memory_working_set_bytes{container=\"$spinSvc\"}[$__interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\"$spinSvc\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Average network ingress/egress for the $spinSvc pods.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 122 },
   "targets": [
    {
     "expr": "avg(\n  sum without (interface) (\n    rate(container_network_receive_bytes_total{pod=~\"$spinSvc.*\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "receive"
    },
    {
     "expr": "avg(\n  sum without (interface) (\n    rate(container_network_transmit_bytes_total{pod=~\"$spinSvc.*\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}